### ISSUE TITLE
System won't boot with custom DTB

### ISSUE THREAD

**Issue by tbanetwork** [hcfman/sbts-base#1]
First of all, thank you for this great project! Without modifications, everything works out of the Box flawlessly.

My Problem is the following:

As soon as I add my custom dtb, which works fine on the initial System, the system won't boot anymore, and I get the following Error-Mesage:

> mount: bad usage
> Try 'mount --help' for more Information.
> -e Can't mount /dev/sda1
> /dev/sda1
> /dev/sda1 on /mnt
> bash: cannot set terminal process group (-1): Inappropriate ioctl for device
> bash: no job control on this shell

Custom DTB configuration in extlinux.conf:

> TIMEOUT 30
> DEFAULT primary
> 
> MENU TITLE L4T boot options
> 
> LABEL primary
>       MENU LABEL primary kernel
>       LINUX /boot/Image
>       FDT /boot/custom.dtb
>       INITRD /boot/initrd
>       APPEND ${cbootargs} quiet root=/dev/mmcblk0p1 rw rootwait rootfstype=ext4 console=ttyS0,115200n8 console=tty0 fbcon=map:0 net.ifnames=0 

Any Ideas/Hints why it does not work?

System Info:
Hardware: Jetson Nano Developer Kit B01
Software: Jetpack 4.6.1 / L4T 3.7.1
Modifications: Custom DTB and Camera Driver as Kernel Module

Any help would be greatly appreciated.

Thank you
Timo

**Comment by hcfman** [comment]
Thanks for the compliment.

Once booting normally, there's a script called make_orig.sh that boots back booting to a normal situation. At this point, maybe you need to do what that script does by hand to get it to boot normally. But I think the key is to get the system booting with the new device tree on the original SD card first and then and only then carrying out the install process. If you have installed this before you will need to ensure that the original extlinux.conf is installed in /boot/extlinux and that the backup and extra ones are not present there, otherwise it thinks that you have installed it already.

In principle, if you can get it to boot with the new device tree into the SD card boot then it should also work on the SSD because at the time of the switch over the device tree should already be in use or everything needed to switch it into place is present on the SSD then.

Kim Hendrikse

**Comment by hcfman** [comment]
Having said that, I haven't tried this but could potentially have a go if you like sometime. I would have to wait for the weekend and I'd need to have the same platform. Is this a nano or an NX ?

**Comment by hcfman** [comment]
Looking at this in a bit more detail. You likely added the custom device tree to the SSD booted system. However, this custom device tree would I expect be needed during the initial kernel booting of the system.

The solution would likely be to:

run

sudo ./sbts-bin/make_orig.sh
reboot

Now you are booted into the original SD. Add the new device tree here.

rm /boot/extlinux/orig_extlinux.cfg /boot/extlinux/readwrite_extlinux.cfg /boot/extlinux/readonly_extlinux.cfg

and then rerun

sudo -H ./sbts-base/sbts_install_base.sh

This should reinstall the target system and make sure that the target system also has the new device tree. But importantly, it first boots off the SD card which the system should now have the new device tree on, when it pivots the root to the new rootfs it will also have the new device tree and everything should work I expect.

**Comment by tbanetwork** [comment]
@hcfman Thank you for your fast response!

I tried what you suggested, but unfortunately it did not fix the issue for me.

Nevertheless, I was able to resolve it by digging through your scripts and comparing it to the Bash Output I posted above. In the end, it's working when i hardcore the path for found_sbtsroot and found_root in overlayRoot.sh.

Original: 

> found_root=$(perl -n -e 'print $1, "\n" if m%^\s*APPEND .*\broot=(\S+)%' /boot/extlinux/extlinux.conf)
> found_init=$(perl -n -e 'print $1, "\n" if m%^\s*APPEND .*\binit=(\S+)%' /boot/extlinux/extlinux.conf)
> found_sbtsroot=$(perl -n -e 'print $1, "\n" if m%^\s*APPEND .*\bsbtsroot=(\S+)%' /boot/extlinux/extlinux.conf)

Edit:

> #found_root=$(perl -n -e 'print $1, "\n" if m%^\s*APPEND .*\broot=(\S+)%' /boot/extlinux/extlinux.conf)
> found_root=/dev/mmcblk0p1
> found_init=$(perl -n -e 'print $1, "\n" if m%^\s*APPEND .*\binit=(\S+)%' /boot/extlinux/extlinux.conf)
> #found_sbtsroot=$(perl -n -e 'print $1, "\n" if m%^\s*APPEND .*\bsbtsroot=(\S+)%' /boot/extlinux/extlinux.conf)
> found_sbtsroot=/dev/sda1

Best regards
Timo

**Comment by hcfman** [comment]
You haven't included the extlinux.cfg that you are using, but if I look at the regexps that fail, I'm guessing that maybe your version of this file contains more than one boot section so that the regexps results in more than one match.

I supposed if I had parsed out the DEFAULT label and restricted the matching to that piece that matches this label it would work. But indeed, I didn't go as far as that.

Glad it's working for you now in any case. Would slightly complicate the perl pieces in the script. If someone else also gets hit by this then I'll consider making the changes to not get tricked by this. (Or next time I work on this).

Are you able to confirm if my assumptions above are correct ?

**Comment by hcfman** [comment]
Hmmm. Your comment I see you set found_sbtsroot=/dev/sda1. However, there is not sbtsroot line in the file contents you show me above. So I think I'm missing some information.

Maybe we should just leave it as solved for you now unless it pops up more frequently then I could look further into a code change. To properly solve it I just run with the same input as you do. But I don't have a custom device tree to play with.

If you would like to solve it permanently we can do that. But I'd need to interact with you a bit more for me to replicate something like your setup.

**Comment by tbanetwork** [comment]
I was finally able to resolve the problem and just wanted to post it here in case anyone got the same problem:

The Entry for the DTB has to be between "LINUX" and "INITRD"

**Not** working extlinux.conf:

> TIMEOUT 30
> DEFAULT primary
> 
> MENU TITLE L4T boot options
> 
> LABEL primary
>       MENU LABEL primary kernel
>       LINUX /boot/Image
>       INITRD /boot/initrd
>       FDT /boot/tba.dtb
>       APPEND ${cbootargs} root=/dev/mmcblk0p1 rw rootwait rootfstype=ext4 console=ttyS0,115200n8 console=tty0 fbcon=map:0 net.ifnames=0 sbtsroot=/dev/sda1
> 
> # When testing a custom kernel, it is recommended that you create a backup of
> # the original kernel and add a new entry to this file so that the device can
> # fallback to the original kernel. To do this:
> #
> # 1, Make a backup of the original kernel
> #      sudo cp /boot/Image /boot/Image.backup
> #
> # 2, Copy your custom kernel into /boot/Image
> #
> # 3, Uncomment below menu setting lines for the original kernel
> #
> # 4, Reboot
> 
> # LABEL backup
> #    MENU LABEL backup kernel
> #    LINUX /boot/Image.backup
> #    INITRD /boot/initrd
> #    APPEND ${cbootargs}

**Working** extlinux.conf:

> TIMEOUT 30
> DEFAULT primary
> 
> MENU TITLE L4T boot options
> 
> LABEL primary
>       MENU LABEL primary kernel
>       LINUX /boot/Image
>       FDT /boot/tba.dtb
>       INITRD /boot/initrd
>       APPEND ${cbootargs} root=/dev/mmcblk0p1 rw rootwait rootfstype=ext4 console=ttyS0,115200n8 console=tty0 fbcon=map:0 net.ifnames=0 sbtsroot=/dev/sda1
> 
> # When testing a custom kernel, it is recommended that you create a backup of
> # the original kernel and add a new entry to this file so that the device can
> # fallback to the original kernel. To do this:
> #
> # 1, Make a backup of the original kernel
> #      sudo cp /boot/Image /boot/Image.backup
> #
> # 2, Copy your custom kernel into /boot/Image
> #
> # 3, Uncomment below menu setting lines for the original kernel
> #
> # 4, Reboot
> 
> # LABEL backup
> #    MENU LABEL backup kernel
> #    LINUX /boot/Image.backup
> #    INITRD /boot/initrd
> #    APPEND ${cbootargs}

Thanks @hcfman for your support!

**Comment by hcfman** [comment]
Super! Thanks for getting back with the solution. And thanks for using the project.
